package jyatlon.core;

/**
 *	-----------------------------------------------------------------------------
 *	----          	  GENERATED on Wed May 20 18:39:44 EDT 2020              ----
 *	-----------------------------------------------------------------------------
 *	DO NOT EDIT THIS FILE - THIS IS A GENERATED CLASS - YOUR CHANGES WILL BE LOST
 *	-----------------------------------------------------------------------------
 *	You must comply with the following instructions in order to do a modification
 *	in this file. Not doing so will see all your changes erased upon regeneration
 *
 *	What file(s) to edit:
 *		- jyatlon/src/main/antlr4/generated/YATL.g4
 *	
 *	How to generate this file (In Eclipse):
 *		- Run As > Java Application: @link StructGen
 *		- Copy console content into file: jyatlon/src/main/java/jyatlon/core/Struct.java
 *
 *	Generator class:
 *		- @link StructGen
 */

import java.util.List;

public class Struct {
	protected final int from;
	protected final int to;

	public Struct(int from, int to) {
		super();
		this.from = from;
		this.to = to;
	}
	public static class ArgExp extends Struct {
		final List<ValueExp> valueExp;
		public ArgExp(int from, int to, List<ValueExp> valueExp){
			super(from, to);
			this.valueExp = valueExp;
		}
	}
	public static class BinaryExp extends Struct {
		final List<ValueExp> valueExp;
		final String unaryOp;
		final List<String> binaryOp;
		public BinaryExp(int from, int to, List<ValueExp> valueExp, String unaryOp, List<String> binaryOp){
			super(from, to);
			this.valueExp = valueExp;
			this.unaryOp = unaryOp;
			this.binaryOp = binaryOp;
		}
	}
	public static class CallExp extends Struct {
		final PathExp pathExp;
		public CallExp(int from, int to, PathExp pathExp){
			super(from, to);
			this.pathExp = pathExp;
		}
	}
	public static class ControlExp extends Struct {
		final String controlOp;
		final String aliasName;
		public ControlExp(int from, int to, String controlOp, String aliasName){
			super(from, to);
			this.controlOp = controlOp;
			this.aliasName = aliasName;
		}
	}
	public static class IfExp extends Struct {
		final LogicalExp logicalExp;
		public IfExp(int from, int to, LogicalExp logicalExp){
			super(from, to);
			this.logicalExp = logicalExp;
		}
	}
	public static class Line extends Struct {
		final List<LineExp> lineExp;
		public Line(int from, int to, List<LineExp> lineExp){
			super(from, to);
			this.lineExp = lineExp;
		}
	}
	public static class LineExp extends Struct {
		final String commentOp;
		final String escapedChar;
		final Value value;
		final ControlExp controlExp;
		final String rawText;
		public LineExp(int from, int to, String commentOp, String escapedChar, Value value, ControlExp controlExp, String rawText){
			super(from, to);
			this.commentOp = commentOp;
			this.escapedChar = escapedChar;
			this.value = value;
			this.controlExp = controlExp;
			this.rawText = rawText;
		}
	}
	public static class LogicalExp extends Struct {
		final List<BinaryExp> binaryExp;
		final List<String> logicalOp;
		public LogicalExp(int from, int to, List<BinaryExp> binaryExp, List<String> logicalOp){
			super(from, to);
			this.binaryExp = binaryExp;
			this.logicalOp = logicalOp;
		}
	}
	public static class Operation extends Struct {
		final String methodName;
		final String aliasName;
		final ArgExp argExp;
		public Operation(int from, int to, String methodName, String aliasName, ArgExp argExp){
			super(from, to);
			this.methodName = methodName;
			this.aliasName = aliasName;
			this.argExp = argExp;
		}
	}
	public static class PathArg extends Struct {
		final String pathName;
		final String aliasName;
		public PathArg(int from, int to, String pathName, String aliasName){
			super(from, to);
			this.pathName = pathName;
			this.aliasName = aliasName;
		}
	}
	public static class PathExp extends Struct {
		final List<PathArg> pathArg;
		final String anyPathOp;
		public PathExp(int from, int to, List<PathArg> pathArg, String anyPathOp){
			super(from, to);
			this.pathArg = pathArg;
			this.anyPathOp = anyPathOp;
		}
	}
	public static class Section extends Struct {
		final PathExp pathExp;
		final List<Line> line;
		public Section(int from, int to, PathExp pathExp, List<Line> line){
			super(from, to);
			this.pathExp = pathExp;
			this.line = line;
		}
	}
	public static class Template extends Struct {
		final List<Section> section;
		public Template(int from, int to, List<Section> section){
			super(from, to);
			this.section = section;
		}
	}
	public static class Value extends Struct {
		final ValueExp valueExp;
		final IfExp ifExp;
		final CallExp callExp;
		public Value(int from, int to, ValueExp valueExp, IfExp ifExp, CallExp callExp){
			super(from, to);
			this.valueExp = valueExp;
			this.ifExp = ifExp;
			this.callExp = callExp;
		}
	}
	public static class ValueExp extends Struct {
		final String valueArg;
		final String aliasName;
		final List<Operation> operation;
		public ValueExp(int from, int to, String valueArg, String aliasName, List<Operation> operation){
			super(from, to);
			this.valueArg = valueArg;
			this.aliasName = aliasName;
			this.operation = operation;
		}
	}
}

